FROM openjdk:22-slim

WORKDIR /app

EXPOSE 8081

CMD ["java", "--illegal-access=warn", "--add-opens", "java.base/java.lang=ALL-UNNAMED", "-cp", "target/bondflix-soap-service-1.0-jar-with-dependencies.jar", "org.Bondflix.Main"]